This is to try to demonstrate an issue we saw in github.ref in
workflow_call workflows.

Ha! My testing wasn't broken as I had expected, and it turns out it
was just fixed **yesterday**: https://github.blog/changelog/2023-09-13-github-actions-updates-to-github_ref-and-github-ref/
